---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether fortune is installed
      ansible.builtin.command: fortune
      register: fortune_installed
      changed_when: False

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: False

    - name: Make sure fortune is installed
      ansible.builtin.debug:
        var: fortune_installed

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
